#!/usr/bin/env bash

CONTAINER=mxcube_dev_qt5g

# This file is for test runs on your local computer and needs to be customised
# It relies on access to existing directories and files on the host, so
# the user ID an parts of the directory tree must be the same on docker and host
# Note that symlinks will gnerally not work if the relevant directory trees differ

# Host-side directories and user info
DOCKER_USER_ID="1000:100"
# DOCKER_USER_ID="1158:3001"
# Mac address used for docker - must match host for GPhL license
MAC_ADDRESS="54:ee:75:b6:8e:d3"

# Host side home directory
USER_HOME="/home/rhfogh"
# host side directory used for docker home (must be different to avoid overwriting)
DOCKER_HOME="/home/rhfogh/dockerhome/"
# Docker side MXCuBE location (mount point) - do not change
MXCUBE_BASE="/MXCuBE"
# Host side MXCuBE location
MXCUBE_ROOT="${USER_HOME}/pycharm"
# NB the docker runs the command "/MXCuBE/mxcubeqt/mxcubeqt/__main__.py", "--pyqt5"]

#
# MXCuBE locations
#
MXCUBE_CORE="${MXCUBE_BASE}/mxcubecore/mxcubecore"
CUSTOM_BRICKS_PATH=""
CUSTOM_HARDWARE_OBJECTS_PATH="${MXCUBE_CORE}/HardwareObjects/mockup"

MXCUBE_GUI_CONFIG_PATH="${MXCUBE_BASE}/mxcubeqt/mxcubeqt/configuration/mockup.yml"
MOCKUP_XML_PATH="${MXCUBE_CORE}/configuration/mockup"
MXCUBE_CORE_CONFIG_PATH="${MOCKUP_XML_PATH}/gphl:${MOCKUP_XML_PATH}/qt:${MOCKUP_XML_PATH}"

# Specific for SOLEIL:
# MXCUBE_CORE_CONFIG_PATH="${MXCUBE_CORE_CONFIG_PATH}:${MXCUBE_CORE}/configuration/soleil/px2/mockups"
MXCUBE_CORE_CONFIG_PATH="${MXCUBE_CORE_CONFIG_PATH}:${MXCUBE_CORE}/configuration/embl_hh_p14/"

# User name - used only for file names etc.
USER_NAME="test_user"

# Additional locations. Must be the same inside and outside docker,
#
# Location for data, matching session base_directory and processed_data_base_directory
DATA_ROOT="/alt/rhfogh/calc/mxcube_data"
# GPhL Software to be found in $GPHL_SOFTWARE_ROOT/GPhL/gphl_release
GPHL_SOFTWARE_ROOT="/alt/rhfogh/Software/"

# End of settable parameters.


xhost +local:
# Command needed to run GPhL workflows
# Add in this for debug
# -p 8050:8050 \
exec docker run -it \
--mac-address $MAC_ADDRESS \
-p 25333:25333 \
-p 25334:25334 \
-h=$CONTAINER \
-u $DOCKER_USER_ID \
-e HOME=$DOCKER_HOME \
-e USER=$USER_NAME \
-e DISPLAY=$DISPLAY \
-e QT_X11_NO_MITSHM=1 \
-e MXCUBE_CORE_CONFIG_PATH=$MXCUBE_CORE_CONFIG_PATH \
-e MXCUBE_GUI_CONFIG_PATH=$MXCUBE_GUI_CONFIG_PATH \
-e CUSTOM_HARDWARE_OBJECTS_PATH=$CUSTOM_HARDWARE_OBJECTS_PATH \
-e CUSTOM_BRICKS_PATH=$CUSTOM_BRICKS_PATH \
-e PYTHONPATH=$MXCUBE_BASE/mxcubeqt:$MXCUBE_BASE/mxcubecore \
-v $MXCUBE_ROOT:/MXCuBE \
-v $GPHL_SOFTWARE_ROOT:$GPHL_SOFTWARE_ROOT \
-v $DATA_ROOT:$DATA_ROOT \
-v $DOCKER_HOME:$USER_HOME \
-v /tmp/.X11-unix:/tmp/.X11-unix \
$CONTAINER
