#! /bin/bash
# Startup script for HardwareRepositoryServer for Proxima beamlines

INSTITUTE=SOLEIL
BEAMLINE=PX1
MXCUBE_ROOT=/data/local/mxcube_v2/mxcube

GUIFILE=$MXCUBE_ROOT/local/${INSTITUTE}/mxcube${BEAMLINE}.gui

exec $MXCUBE_ROOT/local/${INSTITUTE}/startGUI $* ${GUIFILE}


