#! /bin/ksh
# Copyright (c) 2004 Bliss group, ESRF, France
# System startup script for BlissFramework

. blissrc

FRAMEWORKHOME=${BLISSADM}/applications/BlissFramework
PYTHONPATH=`dirname $FRAMEWORKHOME`:${PYTHONPATH}
PYTHON=${BLISSADM}/bin/python

export PYTHONPATH

exec ${PYTHON} ${FRAMEWORKHOME}/startGUI.py $*
