EDNA_TEST_DATA = """<?xml version="1.0" ?>
<XSDataInputMXCuBE>
  <dataCollectionId>
    <value>976533</value>
  </dataCollectionId>
  <diffractionPlan>
    <aimedIOverSigmaAtHighestResolution>
      <value>3.000000e+00</value>
    </aimedIOverSigmaAtHighestResolution>
    <complexity>
      <value>none</value>
    </complexity>
    <maxExposureTimePerDataCollection>
      <value>6.000000e+03</value>
    </maxExposureTimePerDataCollection>
  </diffractionPlan>
  <experimentalCondition>
    <beam>
      <flux>
	<value>2.710000e+12</value>
      </flux>
      <minExposureTimePerImage>
	<value>8.000000e-02</value>
      </minExposureTimePerImage>
      <size>
	<x>
	  <value>5.000000e-02</value>
	</x>
	<y>
	  <value>3.000000e-02</value>
	</y>
      </size>
      <transmission>
	<value>1.000000e+02</value>
      </transmission>
      <wavelength>
	<value>9.136656e-01</value>
      </wavelength>
    </beam>
    <goniostat>
      <maxOscillationSpeed>
	<value>3.600000e+02</value>
      </maxOscillationSpeed>
      <minOscillationWidth>
	<value>5.000000e-02</value>
      </minOscillationWidth>
    </goniostat>
  </experimentalCondition>
  <sample>
    <shape>
      <value>1.000000e+00</value>
    </shape>
    <size>
      <x>
	<value>1.000000e-01</value>
      </x>
      <y>
	<value>1.000000e-01</value>
      </y>
      <z>
	<value>1.000000e-01</value>
      </z>
    </size>
    <susceptibility>
      <value>1.000000e+00</value>
    </susceptibility>
  </sample>
  <dataSet>
    <imageFile>
      <path>
	<value>/data/id29/inhouse/DAS/RAW_DATA/ref-4ESR372D11_1_0001.cbf</value>
      </path>
    </imageFile>
    <imageFile>
      <path>
	<value>/data/id29/inhouse/DAS/RAW_DATA/ref-4ESR372D11_1_0002.cbf</value>
      </path>
    </imageFile>
    <imageFile>
      <path>
	<value>/data/id29/inhouse/DAS/RAW_DATA/ref-4ESR372D11_1_0003.cbf</value>
      </path>
    </imageFile>
    <imageFile>
      <path>
	<value>/data/id29/inhouse/DAS/RAW_DATA/ref-4ESR372D11_1_0004.cbf</value>
      </path>
    </imageFile>
  </dataSet>
</XSDataInputMXCuBE>
"""

EDNA_DEFAULT_INPUT = """<?xml version="1.0" ?>
<XSDataInputMXCuBE>
    <diffractionPlan>
        <aimedCompleteness>
            <value>9.900000e-01</value>
        </aimedCompleteness>
        <aimedIOverSigmaAtHighestResolution>
            <value>3.000000e+00</value>
        </aimedIOverSigmaAtHighestResolution>
        <aimedResolution>
            <value>1.000000e+00</value>
        </aimedResolution>
        <aimedMultiplicity>
            <value>4.000000e+00</value>
        </aimedMultiplicity>
        <complexity>
            <value>min</value>
        </complexity>
        <maxExposureTimePerDataCollection>
            <value>6.000000e+03</value>
        </maxExposureTimePerDataCollection>
    </diffractionPlan>
    <experimentalCondition>
        <beam>
            <minExposureTimePerImage>
                <value>1.000000e-01</value>
            </minExposureTimePerImage>
            <size>
                <x>
                    <value>1.000000e-01</value>
                </x>
                <y>
                    <value>0.70000e-01</value>
                </y>
            </size>
        </beam>
        <goniostat>
            <maxOscillationSpeed>
                <value>3.600000e+02</value>
            </maxOscillationSpeed>
            <minOscillationWidth>
                <value>2.000000e-01</value>
            </minOscillationWidth>
        </goniostat>
    </experimentalCondition>
    <sample>
        <size>
            <x>
                <value>1.000000e-01</value>
            </x>
            <y>
                <value>1.000000e-01</value>
            </y>
            <z>
                <value>1.000000e-01</value>
            </z>
        </size>
        <susceptibility>
            <value>1.000000e+00</value>
        </susceptibility>
    </sample>
</XSDataInputMXCuBE>
"""
