#! /bin/bash
# Startup script for HardwareRepositoryServer for Proxima beamlines

INSTITUTE=SOLEIL
BEAMLINE=29

GUIFILE=/home/blissadm/mxcube/local/${INSTITUTE}/mxcube${BEAMLINE}.gui

exec /home/blissadm/bin/startGUI $* ${GUIFILE}

