#! /bin/bash
# Startup script for HardwareRepositoryServer for Proxima beamlines

INSTITUTE=SOLEIL
BEAMLINE=PX2

GUIFILE=/home/blissadm/mxcube/local/${INSTITUTE}/test.gui

exec /home/blissadm/bin/startGUI $* ${GUIFILE}

