#!/bin/bash
# Startup script for HardwareRepositoryServer for Proxima beamlines

INSTITUTE=SOLEIL
BEAMLINE=PX1
MXCUBE_ROOT=/home/blissadm/mxcube

GUIFILE=$MXCUBE_ROOT/local/${INSTITUTE}/xfeSpectrum.gui

exec $MXCUBE_ROOT/local/${INSTITUTE}/startGUI $* ${GUIFILE}


